# Generated by Django 3.1.2 on 2020-11-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='region',
            field=models.CharField(choices=[('1', 'Metropolitana'), ('2', 'Coquimbo'), ('3', 'Maule'), ('4', 'Araucania')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pack',
            field=models.CharField(choices=[('1', 'ORO HD'), ('2', 'PLATA HD'), ('3', 'BRONCE HD'), ('4', 'ORO 4K'), ('5', 'PLATA 4K'), ('6', 'BRONCE 4K')], max_length=50),
        ),
    ]
